### ISSUE TITLE
PP&A Organización

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/JDPM#116]
Ayudar a mis hermanas en la organización de varios temas administrativos de la firma.

**Comment by jdpalermo** [comment]
Reunion del 14 de Febrero

- [ ] Yo: Opciones para reemplazo de Processmaker
- [ ] Yo: Definir los requerimientos que tienen para las modificaciones a las oficinas en cuanto al re-cableado del Rack
- [ ] Nuria: Investigar Costo mensual del SAP por usuario y compañia.
- [ ] Nuria: Investigar la diferencia de los 3MM
- [ ] Luis: Levantar requerimiento de Fibra Optica para internet.

**Comment by jdpalermo** [comment]
El SAP tiene un costo mensual de $580.00 ($6,660.00 anual)

**Comment by jdpalermo** [comment]
La internet tiene un costo de instalación de $150.00 y para 5MB con lo que empezaríamos tiene un costo de $70.00 mensuales que no esta mal. 

Propuesta: https://www.dropbox.com/s/srbgxu840n4qb5y/PALERMO%20%26%20PALERMO%20-%20PROPUESTA%20DE%20INTERNET.pdf?dl=0

**Comment by jdpalermo** [comment]
Manito Bello
Gracias por tomarte el tiempo para esto, te lo agradezco mucho, estos días he estado pensando mucho en lo que hacemos y cambios que creo que son necesarios. Pero en este email me voy a concentrar en responder lo que preguntas y comentarios para ver si podemos ir tomando decisiones. 

Mi pregunta es: 

¿QUE ESTAS BUSCANDO SOLUCIONAR? 
Si me dices que estas buscando un programa que te reemplace el SAP, te diría que es una opción viable porque es algo similar.  Pero ten en cuenta el problema de internet.  Compara si el peachtree no hace lo mismo, que es un programa que ya muchos contadores utilizan. 

Si me dices que estas buscando algo que te ayude administrativamente a organizar las cuentas de tus clientes, te diría que en lo que vi no me pareció que ese sea su fuerte, lo va a hacer pero como ya lo hace el programa contable que tienes, el problema ahora mismo no es el programa que tienes, es la forma en la que lo están utilizando.   Esta enfocado a contabilidad con poca información administrativa y como no estas acostumbrada a pedir dicha información, parece algo abrumador. 

Hay 2 cosas que necesitamos. 

1. SAP: ver si seguimos con este sistema o pasamos a otro menos costoso pero que cumpla con nuestras necesidades contables. Hablando del SAP, eliminamos el usuario de Nuria que costaba 100 y piquito al mes, y que ella use el de Dalyeris o Isis cuando necesite, allí es un ahorro, de todas formas continúa siendo una mensualidad alta. Entiendo que en su momento inclusive Nuria sugirió el cambio a SAP por ser mas sencillo para lo que hacíamos por tantas cuentas de clientes y tantos gastos, pero tal vez también era porque podemos ligarlo en algún momento al processmaker, algo que ya no va a pasar. De ser así, en verdad podríamos migrar a otro tipo de aplicación de contabilidad, como peachtree que es de uso usual entre los contadores. De todas formas voy a mandarle un email a Dalyeris consultando porque fue que cambiamos de sistema. 

2. Reemplazo para el processmaker. Necesitamos un sistema que básicamente reemplace el processmaker, el cual usamos básicamente para crear los casos, que pasan en ese mismo sistema a una proforma que luego pasa a una orden de venta (en el sistema contable) y que cuando el cliente paga se convierte en una factura (en el sistema contable). 

Obviamente los sistemas tipo processmark pueden ser utilizados para muchas cosas, pero para lo que nosotras lo usábamos era para crear casos, incluir allí mismo los gastos, los honorarios, y luego pasarlo a contabilidad. Y crear lo casos quiere decir llevar un control de los servicios que estamos brindando, a quien, etc. Ya!!! Es mentira decir que lo usábamos para otras cosas. 

MI RECOMENDACION
Creo que debes aprovechar estos días que hay menos trabajo para tener una retroinspeccion de que es lo que quisieras lograr en la firma, en la parte administrativa-Contable-Operativa
Esto lo tienes que escribir para poder plasmarlo en palabras que otra persona te pueda ayudar a resolver, y que a la ves te hace entender si de verdad es un problema real o es un problema de simple percepción personal. 

Si, tienes toda la razón. He estado pensando, analizando, escuchando a otras firmas, viendo como funcionan, y sí, creo que necesitamos analizar cómo estamos operando, sobre todo por los números que vimos antes de la cuarentena. No es que nos va mal, pero básicamente trabajamos para pagarle a los empleados y mandar alguito ahorros. 

Inclusive si estuviéramos mejor organizadas creo que requerimos 1 persona menos en la oficina. Porque para  2 abogadas, que aunque prestan muchos servicios (mal pagados, que eso es otro tema que también estamos viendo) tenemos 1 recepcionista, 1 contadora, 1 asistente contable, 1 administradora, 1 pasante, 1 mensajero. Es decir, para 2 abogadas, tenemos 4 personas en personal administrativo. A Carmichel y Fernando no los cuento dentro de este grupo administrativo porque como lo hablamos antes son personal esenciales para desarrollar los servicios legales como tal, para operar como tal. Somos 2 contra 4, eso es mucho, para 2 abogadas conozco firmas que no tienen ni contador de planta, menos asistente contable, a mucha fuerza una administradora que hace varios roles y alguien de recepción que también hace trámites legales y etc. Entonces pienso que tenemos mucho personal. Si vamos a seguir con tanta gente, hay que brindar mas servicios, legales, administrativos, contables, entre otros, y cobrar mejor. 

Define: 
1. ¿Cúal es el problema actual?

2. ¿Por qué es un problema?

3. ¿Cómo quisieras que fuera una ves resuelto?

Piénsalo desde tu punto de vista como gerente y dueña. Esto puede ser dividido en varias áreas o problemas.

Ej. DESDE MI PERSPECTIVA EXTERNA

Departamento de contabilidad:
1. ¿Cúal es el problema actual?
Es básicamente tu departamento mas grande, tienes una contadora con un salario medio pero considerable comparado al resto, tiene una asistente contable con un salario medio y se apoyan en la recepcionista para algunas tareas, por lo que parte de su costo también va a asociado a la contabilidad.   (sin mencionar las horas que le dedica el personal de Parque y Nuria a ver las cosas de su contabilidad)  Sin embargo, siendo tu costo de personal mas alto son las que menos te producen de ingresos y aun cuando su trabajo se completa y presentas declaraciones de renta, tu como gerente no recibes la información que necesitas para tomar las desiciones importantes.    

Tus cuentas por cobrar, no las ves claramente, siempre que revisamos los documentos y algo salta a la vista, no se tiene la respuesta inmediata sobre el porque, sino que hay que investigar y esperar;   
Las cuentas de depósitos de clientes tampoco estan claras; 
Los gastos y costos de la oficina no te son claros porque se mezclan con los que traen para bajar la renta
TOTALMENTE. No deberíamos pedir informes, nos deberían rellenar de informes, es broma, no rellenar, pero los básicos. Mi trabajo es buscar clientes, atenderlos, trabajarlos, mantenerlos felices, producir, y solo revisar la parte contable y administrativa. 

2. ¿Por qué es un problema?
El problema es que estas gastando recursos económicos y no estas recibiendo a cambio lo que tu esperas, si no únicamente lo que ellas consideran su trabajo. TOTALMENTE. 

Qué crees que debemos o podemos hacer? Crees que daba pedirle a cada empleado que me envíe un listado de sus funciones actualizado? para ver que hace cada uno y partir de allí. 

Gracias
JP
