### ISSUE TITLE
Registro de Salvoconductos 

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/JDPM#197]
Rosa - Directora de Comercio - 504-4332
Eric Jaramillo - 6615-7026 Abogado de la dirección. Nedelka de Moreno dio el contacto.
Panama Emprende - Aviso de Operación - 560-5872 

Decreto 507 art 2 numeral 30 acapite B - para actividades funerariasEmpresas a Registrar

- [ ] Parque del Recuerdo: 
Estamos teniendo problema con el aviso de operaciones. Pero vamos a corregirlo en Panama emprende a ver si con eso ya pasa. 
     - [ ] Corrección del Aviso de Operaciones - Carmichell

- [ ] PEC Panama:
     - [x] Corrección del Aviso de Operaciones - Carmichell

- [ ] Rancho Hato Viejo
- [ ] Ganadera Rio Chico
- [ ] Almofi
