### ISSUE TITLE
La Pradera - Perfeccionar la Compraventa

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/JDPM#23]
Para perfeccionar la compraventa de La Pradera aun tenemos una serie de pasos que dar.

- [ ] Pago de los impuestos de transferencia 2% y 3%

- [ ] Entrega de Paz y Salvo del PH

- [ ] Entrega de Minuta de venta

- [ ] Confección de Protocolo

- [ ] Inscripción en el Registro Publico
