### ISSUE TITLE
Chef´s Box - Organización Legal

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/JDPM#284]
- [x] Fifo: Que permisos necesitamos y que tan duro es conseguirlos
- [x] PP&A: Nombre Comercial 
- [x] PP&A: Actividades en aviso de operación
- [x] PP&A Averiguar que permisos necesitamos para esas actividades
