### ISSUE TITLE
LRTC - Macrogym

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/JDPM#3]
Macrogym es el software que mejor se acomoda a nuestra necesidad en la piscina.  

- [ ] Revisión de la versión Standard
- [ ] Compra de versión
- [ ] Implementación
- [ ] Compra de Hardware
- [ ] Instalación

**Comment by jdpalermo** [comment]
@AlexandraChen esta estaba duplicad? que quieres que haga con el? Un REUSE o le quito el valor y lo mando a Closed?

**Comment by AlexandraChen** [comment]
Puedes quitarle todo y reusarla o cerrarla. @jdpalermo
