### ISSUE TITLE
LRTC - Re apertura

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/JDPM#499]
Los siguientes puntos son importantes para la re-apertura

- [ ] Organizar los alquileres
     - [ ] Hacer contratos 2020 para cada local
     - [x] Cobro de luz a Carlos Pena Herrera
          - [ ] Conseguir los estados de cuenta de luz de los últimos 6 meses
     - [x] Limpieza del Local 4
     - [x] Organizar los Depósitos

.
- [ ] Sistema de cobras y entradas
     - [ ] Revisar como estamos con el Macrogym
     - [ ] Torniquete de entrada
     - [ ] Firestec para tienda / Equipo de Ranchito

.
- [ ] Clubes:  Reunion 

.
- [ ] Instalaciones
     - [ ] Verificar si hay que resellar la piscina
     - [x] Limpieza general del area
     - [ ] Medidor para el local de Carlos Pena Herrera
     - [ ] Letreros de Covid.

**Comment by jdpalermo** [comment]
Local 1: $350.00 
Local 2: $250.00
Local 3: $350.00
Local 4: a ser definido
