### ISSUE TITLE
Organización y cambios de operación

### ISSUE THREAD

**Issue by jdpalermo** [GrupoPalermo/JDPM#705]
[https://app.zenhub.com/files/229819746/fb11e0e6-6131-4711-a84f-ae344bf89108/download](https://app.zenhub.com/files/229819746/fb11e0e6-6131-4711-a84f-ae344bf89108/download)

CRONOGRAMA

DOMINGO 24 DE ENERO:
- [ ] PRESENTACION DE OFERTA DE TRABAJO PARA EL CHEF MILANES

LUNES 25 DE ENERO:
- [ ] ABONO No.1 CHEF MILANES
- [ ] INICIO DE PARTE DEL CHEF DEL MENU Y PROCEDIMIENTOS
- [ ] RECOMENDACIONES PARA REMODELACION DE COCINA Y EQUIPOS NECESARIOS

DEL 26 DE ENERO AL 1 DE FEBRERO:
 - [ ] COTIZACION DE OBRA DE COCINA
 - [ ] COMPRA DE MATERIALES PARA REMODELACION
 - [ ] COTIZACION DE EQUIPOS NUEVOS DE COCINA

DEL 2 DE FEBRERO AL 14 DE FEBRERO:
 - [ ] REMODELACION DE COCINA CON FECHA DE ENTREGA EL 14 DE FEBRERO
 - [ ] ENTREVISTA Y CONTRATACION DE PERSONAL CALIFICADO PARA COCINA

LUNES 15 DE FEBRERO:
 - [ ] APERTURA DEL LOCAL CON MENU ACTUAL
 - [ ] ABONO No. 2 CHEF MILANES
 - [ ] ENTREGA DEL MENU CON SUS PORCIONES 
 - [ ] INICIO DE PRODUCCION CON NUEVAS PORCIONES
 
LUNES 1 DE MARZO:
 - [ ] ABONO No.3 CHEF MILANES
 - [ ] IMPLEMENTACION DE NUEVO MENU
 - [ ] ENTREGA DE PROCEDIMIENTOS AL PERSONAL DE LA COCINA

DEL 2 AL 31 DE MARZO:
 - [ ] SEGUIMIENTO POR PARTE DEL CHEF DEL CUMPLIMIENTO DE PROCEDIMIENTOS  

P.D. (SOLO PARA SOCIOS)

-LOS ABONOS SE LES PONDRA CIFRA CON LA CREACION EN CONJUNTO POR PARTE DE TODOS LOS SOCIOS DE LA PROPUESTA.
-ESTOY ESPECULANDO SOBRE LOS TIEMPOS DE ENTREGA DEL CHEF, CUANDO ACEPTE LA PROPUESTA DEBERIAMOS RECIBIR UN CRONOGRAMA DE EL Y ADAPTARLO AL NUESTRO.

-RECIBAMOS ASESORIA DE PARTE DEL CHEF SOBRE LA POSICION DE “GERENTE DE COCINA” SI ES UNA POSICION VIABLE O LA CONTRATACION DE UN 4to. COCINERO QUE SEA EL JEFE DE COCINA Y ASUMA LA RESPONSABILIDAD DE LO QUE SALE, QUE PARA MI LE SACARIAMOS MAS PROVECHO (REVISAR ARCHIVO DE ESTRUCTURA DE TRABAJO)

-A PARTIR DE LA FECHA HASTA EL 1 DE FEBRERO DEBERIAMOS ENTREVISTAR UNA PERSONA PARA LA POSICION DE ADMINISTRADORA GENERAL O SECRETARIA EJECUTIVA PARA QUE COMIENZA A TRABAJAR CON NOSOTROS EN EL PERIODO DEL 2 AL 15 DE FEBRERO; TAREA PARA MINO Y ALEX

**-DEL 2 AL 15 DE FEBRERO ENTRENAMIENTO PARA SECRETARIA Y CREACION DE PROCEDIMIENTOS PARA ELLA; TAREA PARA MINO, MONICA Y FIFO**

**-DEL 18 DE ENERO AL 14 DE FEBRERO ORGANIZACIÓN DEL LOCAL, MEJORAR IMAGEN, MEJORAR LIMPIEZA, ORGANIZACIÓN DE LA LOGISTICA DE TRABAJO; TAREA PARA MINO, ALEX Y FIFO.**
